### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by ank1traj** [ank1traj/testcase-generator#16]
Currently, our website is missing a footer section. This makes the website design look incomplete and unprofessional. To improve the user experience and make our website look more polished, we should add a footer section.

The footer section will be located at the bottom of every page and will include important information such as the company name, copyright information, contact information, and links to important pages such as the About Us page and Terms of Service.

The footer should be designed to match the overall theme and color scheme of the website. It should be visually appealing and easy to navigate. The links in the footer should be clickable and lead to the appropriate pages.

Adding a footer section will not only improve the website design but also provide important information to our users and improve their overall experience on our website. Therefore, we should prioritize this issue and add a footer section as soon as possible.

**Comment by saimadhav24** [comment]
Can i try this one?

**Comment by ank1traj** [comment]
Hi @saimadhav24 

That sounds great! Thank you for expressing your interest in adding a footer. We welcome any contributions that can enhance the user experience of our platform. Please feel free to take the issue. We look forward to seeing your contributions.

Thanks 😊

**Comment by saimadhav24** [comment]
@ank1traj Thank you

**Comment by saimadhav24** [comment]
@ank1traj Wt links shd be put in footer?

**Comment by ank1traj** [comment]
@saimadhav24 For now you can put dummy data. Later we'll change that accordingly.

**Comment by saimadhav24** [comment]
@ank1traj You fix it, i will try to finish it by that date

**Comment by saimadhav24** [comment]
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: test-generator@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4   
npm ERR! node_modules/@material-ui/core
npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!   node_modules/@material-ui/icons
npm ERR!     @material-ui/icons@"^4.11.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\SAI MADHAV\AppData\Local\npm-cache\_logs\2023-04-10T03_18_54_118Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SAI MADHAV\AppData\Local\npm-cache\_logs\2023-04-10T03_18_54_118Z-debug-0.log
```
I was getting this error while installing packages, itseems there is a conflict between material-ui requirement and reactjs version,
yesterday i used `npm i --force` but i think it resulted in incorrect ouputs

**Comment by ank1traj** [comment]
> ```
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR! 
> npm ERR! While resolving: test-generator@0.1.0
> npm ERR! Found: react@18.2.0
> npm ERR! node_modules/react
> npm ERR!   react@"18.2.0" from the root project
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4   
> npm ERR! node_modules/@material-ui/core
> npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
> npm ERR!   node_modules/@material-ui/icons
> npm ERR!     @material-ui/icons@"^4.11.3" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR!
> npm ERR! For a full report see:
> npm ERR! C:\Users\SAI MADHAV\AppData\Local\npm-cache\_logs\2023-04-10T03_18_54_118Z-eresolve-report.txt
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\SAI MADHAV\AppData\Local\npm-cache\_logs\2023-04-10T03_18_54_118Z-debug-0.log
> ```
> 
> I was getting this error while installing packages, itseems there is a conflict between material-ui requirement and reactjs version, yesterday i used `npm i --force` but i think it resulted in incorrect ouputs
> 
> **edit: i think i resolved it**

Always try to pull the latest code @saimadhav24

**Comment by ank1traj** [comment]
@saimadhav24 Can we do subscribe little better?

**Comment by saimadhav24** [comment]
@ank1traj This is a new design that i am thinking it will be good looking, what is your opinion

![image](https://user-images.githubusercontent.com/124759892/231267734-27814ffb-a395-4851-a5e4-2d1b6838e9d8.png)

**Comment by saimadhav24** [comment]
This is another design:

![image](https://user-images.githubusercontent.com/124759892/231271894-f8859ddf-d3dd-4edc-b703-7880eb2c751e.png)

on hovering it becomes like this:

![image](https://user-images.githubusercontent.com/124759892/231272048-6d6eebc3-1cb9-436c-bfe1-7ae72c8ec417.png)

The differnce is:
It zooms a bit on hovering and changes the color

**Comment by saimadhav24** [comment]
This is another design:

![image](https://user-images.githubusercontent.com/124759892/231274960-d44c2775-4eb4-416e-884b-6a32a03ee2a5.png)

On hovering, it turns into something like this:

![image](https://user-images.githubusercontent.com/124759892/231275029-f615708d-c337-4e86-b4d6-fe28cabdebcd.png)

**Comment by ank1traj** [comment]
@saimadhav24 There is no need of first name and last name. Only email ID is enough. Also, if possible then keep the button and input in the same div(same line).

**Comment by saimadhav24** [comment]
I tried keeping button and input in same line but the result was not that good

**Comment by saimadhav24** [comment]
I will remove first_name and last_name

**Comment by ank1traj** [comment]
On the small device you can keep it in two line. Take this example https://startup-gules.vercel.app/

**Comment by saimadhav24** [comment]
@ank1traj Hello, so i have been working on footer thing, and i had few problems so couldnt update you, here are few screenshots of new design:

![image](https://user-images.githubusercontent.com/124759892/231870015-65b166f1-39b1-43ab-98cb-f17e7fd821ec.png)

![image](https://user-images.githubusercontent.com/124759892/231870089-73875ef7-fbb9-4f1d-bd28-c774f68adb20.png)

![image](https://user-images.githubusercontent.com/124759892/231870182-d05f775a-5aeb-4d8b-9644-ecbb8dec215c.png)


**Note: I know that still i have to modify them, this is just a prototype**

**Comment by ank1traj** [comment]
Good work @saimadhav24.

**Comment by saimadhav24** [comment]
@ank1traj I am just discovered this issue, when on homepage in a smaller screen:

![image](https://user-images.githubusercontent.com/124759892/232020924-e1fba09e-1772-4a4f-a0e2-d1ab119dcb1c.png)

the footer is getting faded away by some additional element, any idea how to prevent it?

**Comment by ank1traj** [comment]
@saimadhav24 You can fix this

**Comment by saimadhav24** [comment]
@ank1traj Was able to fix the gradient, but found out a new issue , u can see it in the following pic:

![image](https://user-images.githubusercontent.com/124759892/232040799-c27ddf8f-7f32-4e50-842f-6263d590bd97.png)

the part "By Ankit Raj" is floating all over the page, will be working on it

**Comment by saimadhav24** [comment]
@ank1traj I think this is fine for now

![image](https://user-images.githubusercontent.com/124759892/232182611-e6981e68-293b-4bb7-81dc-cd8b007740c4.png)
<hr/>

![image](https://user-images.githubusercontent.com/124759892/232182700-f2392b93-9d8a-488a-ba76-40510cb78426.png)
<hr/>

![image](https://user-images.githubusercontent.com/124759892/232182631-914542ef-a703-4816-b8b2-054c509f9f8b.png)

**Comment by ank1traj** [comment]
@saimadhav24 either you can bring the name in centre or remove that.

**Comment by saimadhav24** [comment]
Update:
* Removed the name for smaller screens 
* for larger screens, href for "By Ankit Raj " was not working so fixed it, removed this from css(pointer-events: none;)
![image](https://user-images.githubusercontent.com/124759892/232223084-1bd2ae6d-edea-4025-a1d3-aacefe20ae2b.png)

**Comment by saimadhav24** [comment]
@ank1traj Do you want me to raise a pr? or do you need any more changes?

**Comment by ank1traj** [comment]
You can raise the PR @saimadhav24

**Comment by saimadhav24** [comment]
Hey @ank1traj , what should i mention for this:

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

**Comment by ank1traj** [comment]
> Hey @ank1traj , what should i mention for this:
> 
> # How Has This Been Tested?
> Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> 
> * [ ]  Test A
> * [ ]  Test B
> 
> **Test Configuration**:
> 
> * Firmware version:
> * Hardware:
> * Toolchain:
> * SDK:
> 
> # Checklist:
> * [ ]  My code follows the style guidelines of this project
> * [ ]  I have performed a self-review of my own code
> * [ ]  I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [ ]  My changes generate no new warnings
> * [ ]  I have added tests that prove my fix is effective or that my feature works
> * [ ]  New and existing unit tests pass locally with my changes
> * [ ]  Any dependent changes have been merged and published in downstream modules

Hi @saimadhav24,

You can add your system configuration.

**Comment by saimadhav24** [comment]
Thank you @ank1traj , I will be raising pr by tonight or by tmrw evening

**Comment by saimadhav24** [comment]
@ank1traj Hi, I need some time to create PR, I am currently busy with my college reviews, I will create PR as soon as I finish my review

**Comment by saimadhav24** [comment]
@ank1traj , Hi , I have raised PR with whatever details i know, you can check it once and let me know if anything has to be changed, thank you
