### ISSUE TITLE
Error While Installing "testcase-generator" project Locally

### ISSUE THREAD

**Issue by Shahid-Bagwan** [ank1traj/testcase-generator#20]
**I encountered an error while Installing "testcase-generator" project locally. The error message reads:**

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: test-generator@0.1.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR! node_modules/@material-ui/core
npm ERR!   peer @material-ui/core@"^4.0.0" from @material-ui/icons@4.11.3
npm ERR!   node_modules/@material-ui/icons
npm ERR!     @material-ui/icons@"^4.11.3" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\shanu\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```
**I am using React version 18.2.0, which is required by my project. However, the "@material-ui/core" package requires a version of React that is either 16.8.0 or 17.0.0, causing a conflict in the dependency tree.**

**I Resolved this error using "npm install --force". The Development Section In The Readme File Must Be Updated To Help The New Developers To Avoid This Issue.**

**Comment by ank1traj** [comment]
Hi @Shahid-Bagwan 

Thanks for pointing but I would suggest you, pull the latest code and then try it. We stopped using ```@material-ui/core```. Let me know if the latest code is still throwing this error. 

Thanks😊

**Comment by Shahid-Bagwan** [comment]
> Hi @Shahid-Bagwan
> 
> Thanks for pointing but I would suggest you, pull the latest code and then try it. We stopped using `@material-ui/core`. Let me know if the latest code is still throwing this error.
> 
> Thanks 😊

Hello @ank1traj 

I tried but It's showing the same error message.

**Comment by ank1traj** [comment]
Hi @Shahid-Bagwan 

What I will suggest you delete the node modules folder, yarn.lock or package.lock and then pull the code or freshly clone the repo and then try it once again. As I told you it's weird that you're getting errors for that package which we're not using anymore. Please let me know after this. 

Thanks 😊

**Comment by Shahid-Bagwan** [comment]
hey @ank1traj 

Yes I would do that.

thanks!

**Comment by ank1traj** [comment]
@Shahid-Bagwan Did you try again?

**Comment by Shahid-Bagwan** [comment]
Hello @ank1traj 

Yes It worked 😊.
