### ISSUE TITLE
docs: redesigned the README.md file & add contributing.md file

### ISSUE THREAD

**Issue by priyankarpal** [ank1traj/testcase-generator#29]
- In README.md we are using basic design/structure but we can customize it. such as we can add tech stacks, links, etc.
- Also, we can add separate contributing guide files that will help newcomers to create their first PR

**Comment by ank1traj** [comment]
Congratulations on opening your first issue to the project! We will triage this shortly.

**Comment by ank1traj** [comment]
@priyankarpal Assigned the issue. All the best.

**Comment by priyankarpal** [comment]
> @priyankarpal Assigned the issue. All the best.

thank you
