### ISSUE TITLE
[Bug]: fix the Navbar

### ISSUE THREAD

**Issue by priyankarpal** [ank1traj/testcase-generator#39]
### What happened?

Clicking on the nav link causes the automatic disappearance of other links.

https://user-images.githubusercontent.com/88102392/232265218-8dce9a8f-c90c-4e07-bfe3-952df83c5f71.mp4

### Version

1.0.0 (Default)

### What OS are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ank1traj** [comment]
Hi @priyankarpal,

This will not consider as a bug. If I am on contact page then there is no need of contact link in the navbar, same for the about also. I hope this is clear to you.

**Comment by priyankarpal** [comment]
ok
